### ISSUE TITLE
Dependent proto messages should not need to be in dependency order

### ISSUE THREAD

**Issue by 7sharp9** [jet/falanx#1]
**Is your feature request related to a problem? Please describe.**
Dependent types need to be in dependency order in order for the generator to work.

**Describe the solution you'd like**
A topological sort of the proto types should be done by the generator.

**Describe alternatives you've considered**
Manual ordering in the proto file.

**Additional context**
None.

**Comment by vchekan** [comment]
Isn't this one solved with `namespace rec`?

**Comment by 7sharp9** [comment]
No, its unrelated.

**Comment by 7sharp9** [comment]
Fixed in 0.5.0 release
