### ISSUE TITLE
support package directive

### ISSUE THREAD

**Issue by et1975** [jet/falanx#36]
**Is your feature request related to a problem? Please describe.**
proto's `package Sample.Messaging;` directive currently stops the codegen output w/o any error.
No code is emitted beyond the namespace/open statements.

**Describe the solution you'd like**
Error out until the `package` directive can be supported. Once supported open a namespace using the name provided for the types following the directive.

**Describe alternatives you've considered**
Remove the directive.

**Additional context**
n/a.

**Comment by 7sharp9** [comment]
#42 Should address this?

**Comment by enricosada** [comment]
@7sharp9 @et1975 there is an example proto?
Will be nice to add an example to the test suite (just adding another sample)

**Comment by et1975** [comment]
```proto
syntax = "proto3";

package Sample.Tests;

message BundleRequest {
  int32 martId = 1;
  string member_id = 2;
  string channel_type = 3;
  repeated string retail_skus = 4;

}
```

**Comment by enricosada** [comment]
ok, i refactored a bit the test suite with #54 

now is easier to add a test, you just need to add a proto, and a f# file with code for serialize/deserialize, and choose what template to use (binary/json/binary+json)

i added the test with https://github.com/jet/falanx/pull/55 .

the code will use for the expected namespace https://github.com/jet/falanx/commit/c70d6e817140390266db40ee27e5151e4a3465d9#diff-8a09d5df40a7fc279bd7b10d3c4f324dR3 so will fail if generator doesnt use that

as a note, later these tests will be used also to interop .net <-> scala tests

**Comment by enricosada** [comment]
Closing.

implemented and test added
