### ISSUE TITLE
`oneof` sub-messages

### ISSUE THREAD

**Issue by et1975** [jet/falanx#37]
**Is your feature request related to a problem? Please describe.**
`oneof` messages defined like this currently fail to codegen:
```proto
message Poll {
}

message Discover {
}

message Command {
  oneof sub {
    Poll poll = 1;
    Discover discover = 2;
  }
}
```

>Failed to serialize property Item: Poll. Error: System.Exception: Void writeEmbedded(Int32, Froto.Serialization.ZeroCopyBuffer, Falanx.BinaryCodec.IMessage) is not generic
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1645.Invoke(String message)
   at Falanx.BinaryGenerator.Serialization.serializeProperty(FSharpExpr buffer, FSharpExpr this, PropertyDescriptor prop)

**Describe the solution you'd like**
It's a perfectly valid construct and should be supported.

**Describe alternatives you've considered**
Can't think of any.

**Additional context**
n/a.

**Comment by 7sharp9** [comment]
Added by @kevmal  👍
