### ISSUE TITLE
Proto file is not re-generated

### ISSUE THREAD

**Issue by vchekan** [jet/falanx#67]
**Describe the bug**
Sometimes proto files are not re-generated.

**To Reproduce**
I've opened example-sdk/example2 solution and compiled it. Then added a field to bundle.proto and recompiled project. I've got an error about missing member as expected, because I have not corrected .cs code. Then I've removed the filed I've added to proto file (i.e. restored original .proto) and recompiled the project. Error remained and output suggested proto file was not recompiled. 

**Expected behavior**
Proto file should be recompiled and error should be gone.

**Environement (please complete the following information):**
 - OS: windows
 - Framework dotnetcore-2.1

**Comment by enricosada** [comment]
Closing, fixed with #98
