### ISSUE TITLE
Uneeded dependencies

### ISSUE THREAD

**Issue by vchekan** [jet/falanx#68]
**Describe the bug**
`example-sdk/example2` dependencies include things like `Froto.Parser` which are most definitely not needed at runtime.

**Expected behavior**
Only dependencies needed at runtime should be included into projects which use Falanx to generate code.

**Environement (please complete the following information):**
 - OS: windows
 - Framework netcode-2.1

**Comment by 7sharp9** [comment]
So `Froto.Parser` is it coming in via `Falanx.Proto.Codec.Binary`, I don't think it's a direct dependency.

**Comment by vchekan** [comment]
Addressed in 0.4.0-alpah2 release
