### ISSUE TITLE
Default namespace option must not be mandatory

### ISSUE THREAD

**Issue by vchekan** [jet/falanx#74]
**Is your feature request related to a problem? Please describe.**
When integrating with msbuild, it is impractial to demand to pass namespace as command line tool because it requires hacking project files.

**Describe the solution you'd like**
Implement namspace option support in.proto file and remove mandatory command line option `--defaultnamespace`

**Comment by enricosada** [comment]
protobuff namespace support is implemented, falanx support the `package` directive (ref https://github.com/jet/falanx/issues/36)

If the .proto file doesnt use the `package` directive, the namespace used is the `RootNamespace` msbuild property, the one used for the default namespace of the project, and already set by msbuild sdk by convention to the project name.
ref https://github.com/jet/falanx/blob/22554cfe216defe78ab95b26f76d311d0e61e43b/Falanx.Sdk/build/Falanx.Sdk.targets#L93

by command line, to make that `--defaultnamespace` optional, we can use the .proto filename

**Comment by enricosada** [comment]
Now the `--defaultnamespace` is optional from command line. if not set, the proto filename will be used as namespace
