### ISSUE TITLE
Do not display "usage" when error in protobuf file

### ISSUE THREAD

**Issue by vchekan** [jet/falanx#76]
**Describe the bug**
Compile protobuf file which contains error (is invalid protobuf file).  Along with protobuf syntax error there will be shown "usage" screen. This is confusing because makes user believe that something in command line was wrong.

**Expected behavior**
Only protobuf syntax error with line number should be shown. No exception stack trace or "usage" screen.

**Comment by enricosada** [comment]
falanx should output error (with a flag is ok) in the VS error format, so can point to file or line

**Comment by vchekan** [comment]
No, i am not talking about error message but about adding "usage" screen to every message. What relation VStudio has to "usage" if error is in .proto syntax?
