### ISSUE TITLE
Example README is incorrect due to missing a missing tools folder and/or steps

### ISSUE THREAD

**Issue by panesofglass** [jet/falanx#8]
**Describe the bug**
The [example](https://github.com/jet/falanx/tree/master/example) describes `cd tools`, but no `tools` folder has been committed.

**To Reproduce**
1. Clone repository
2. `cd example`
3. List files and folders
4. See there is no `tools` folder
5. `dotnet restore` fails as it cannot find a project or solution file

**Expected behavior**
The example README should describe a successful path to running the example.

**Comment by 7sharp9** [comment]
I checked the tools folder in.
