### ISSUE TITLE
Schema compile error does not cause build to fail

### ISSUE THREAD

**Issue by vchekan** [jet/falanx#83]
**Describe the bug**
When there is an error in schema, msbuild by default does not check error code of Exec command and as result, compiler will fail with semi-random error, which makes it hard to troubleshoot.

**To Reproduce**
Delete .fs file. 
Make intentional syntax error in .proto file.
Compile and observe error saying that .fs file is missing.

**Expected behavior**
Error should should indicate that failure happen in schema compilation and not in .fs file compilation.

**Comment by enricosada** [comment]
can repro

**Comment by enricosada** [comment]
fixed
