### ISSUE TITLE
Compiler Warnings with 

### ISSUE THREAD

**Issue by bugra** [jet/falanx#95]
**Describe the bug**
F# record type has compiler warnings with version `Falanx.Sdk 0.4.0-alpha2`.

``` warning FS0686: The method or function 'jfieldOpt' should not be given explicit type argument(s) because it does not declare its type parameters explicitly ```

**To Reproduce**

**Expected behavior**

**Environement (please complete the following information):**
 - OS: osx
 - Framework: netstandard2.0, net462

**Additional context**

**Comment by enricosada** [comment]
@7sharp9 meanwhile the warning are fixed for good in the generated code, it's possibile to add `#nowarn "FS0686"` to that file?

**Comment by 7sharp9** [comment]
This is the way definitions have to be done in Fleece as it used SRTP **heavily**.   If theres an ast node for that we can add it.

**Comment by 7sharp9** [comment]
ast node:
```
HashDirective
             (ParsedHashDirective
                ("nowarn",["FS0686"],
                 /Users/dave.thomas/Documents/GitHub/FsAst/Hello.fs (2,0--2,16) IsSynthetic=false),
              /Users/dave.thomas/Documents/GitHub/FsAst/Hello.fs (2,0--2,16) IsSynthetic=false);
```

**Comment by 7sharp9** [comment]
@enricosada Done?
